export const CLEAR_SQUARES = 'CLEAR_SQUARES'

export const GENERATE_MINES = 'GENERATE_MINES'

export const REVEAL_SQUARE = 'REVEAL_SQUARE'

export const SET_CONFIG = 'SET_CONFIG'

export const SET_GAME_STATE = 'SET_GAME_STATE'
