export const CLEAR_SQUARES = "CLEAR_SQUARES";

export const GENERATE_MINES = "GENERATE_MINES";

export const REVEAL_SQUARE = "REVEAL_SQUARE";

export const SET_GAME_DIFFICULTY = "SET_GAME_DIFFICULTY";

export const SET_GAME_DURATION = "SET_GAME_DURATION";

export const SET_GAME_STATE = "SET_GAME_STATE";

export const SET_LEVEL = "SET_CONFIG";
